{
 "title": "Awesome Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Pizza making latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "purchase_sum{category=\"latency\"}/purchase_count{category=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza making failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "purchase_sum{category=\"latency\"}/purchase_count{category=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(purchase_bucket{category=\"count\"}[1m])",
     "legendFormat": "{{category}}"
    },
    {
     "expr": "rate(purchase_bucket{category=\"revenue\"}[1m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "user_count{source=\"jwt_pizza_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(auth_bucket{category=\"success\"}[1m])",
     "legendFormat": "{{category}}"
    },
    {
     "expr": "rate(auth_bucket{category=\"failure\"}[1m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "system_memory{source=\"jwt_pizza_service\", category=\"used\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "system_cpu{source=\"jwt_pizza_service\", category=\"used\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory{source=\"jwt_pizza_service\", category=\"used\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "system_cpu{source=\"jwt_pizza_service\", category=\"used\"}",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}