{
 "title": "JWT Pizza",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Pizza making latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_latency_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_count_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Count"
    },
    {
     "expr": "rate(pizza_purchase_revenue_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza making failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_error_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_user_count_total{source=\"jwt_pizza_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_http_request_all_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(pizza_http_request_get_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(pizza_http_request_post_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Post"
    },
    {
     "expr": "rate(pizza_http_request_delete_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(pizza_http_request_put_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Put"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pizza_system_memory_used{source=\"jwt_pizza_service\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "pizza_system_cpu_percent{source=\"jwt_pizza_service\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_system_memory_used{source=\"jwt_pizza_service\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "pizza_system_cpu_percent{source=\"jwt_pizza_service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizza_http_latency_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizza_auth_success_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(pizza_auth_failure_total{source=\"jwt_pizza_service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  }
 ]
}